### ISSUE TITLE
This was fixed in vanilla in 1.19.3

### ISSUE THREAD

**Issue by Sshmoob** [LopyMine/CollisionFix#1]
The reason why no 1.20 ports of the original mod were made is because Mojang already fixed this bug in 1.19.3 themselves. Thus, the mod is no longer needed. Just letting you know if you want to take the mod down from Modrinth or at least add a notice to the description.

**Comment by LopyMine** [comment]
Yes, I know, but this mod has one more functionality - it removes collisions with other players, so I ported it to the new version.
I think I should write a simple description so people can understand more about this mod.

**Comment by Sshmoob** [comment]
Maybe call the mod PlayerCollisionFix instead?
