### ISSUE TITLE
[Crash] Mod in 1.20.4 is getting crashed

### ISSUE THREAD

**Issue by PSYCHEER** [LopyMine/CollisionFix#3]
![image](https://github.com/LopyMine/CollisionFix/assets/42911029/6000e7d5-0fbd-4114-b330-dc5f4ffbdba8)

**Comment by venaminecraft** [comment]
Update to 1.20.4 Please 😊

**Comment by LopyMine** [comment]
Now Collision Fix supports versions 1.20 and higher, so it's fixed

**Comment by venaminecraft** [comment]
Thank you so much 🥳
