### ISSUE TITLE
Fabric 1.21.1 

### ISSUE THREAD

**Issue by WhyAreLess** [LopyMine/CollisionFix#4]
Hi! Any plans to update Collision Fix to support 1.21.1? :)

**Comment by LopyMine** [comment]
Hmm, is it doesn't work on 1.21.1?

**Comment by WhyAreLess** [comment]
> Hmm, is it doesn't work on 1.21.1?

You are right. This is my bad.

I never thought of trying the 1.21 version of Collision Fix on 1.21.1 but it did work.

Sorry!
